name: Daily Commit

on:
  schedule:
    - cron: '30 18 * * *'  # 12:00 AM IST
    - cron: '15 19 * * *'  # 12:45 AM IST
    - cron: '30 19 * * *'  # 1:00 AM IST
    - cron: '55 19 * * *'  # 1:25 AM IST
    - cron: '30 12 * * *'  # 6:00 PM IST
    - cron: '30 16 * * *'  # 10:00 PM IST
    - cron: '0 17 * * *'   # 10:30 PM IST
    - cron: '30 17 * * *'  # 11:00 PM IST
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update file with IST time
        run: |
          TZ='Asia/Kolkata' date >> update.md
          echo "Random: $RANDOM" >> update.md
          echo "---" >> update.md

      - name: Commit changes
        run: |
          git config --global user.name "anujrwt08"
          git config --global user.email "anujrwt08@gmail.com"
          git add update.md
          git commit -m "Daily update [skip ci]" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
